### PR TITLE
Change the n items to n resource name in record lists

### LINKED ISSUE #1014: Change the N items to N {resource name} in record lists
## Description of the bug

_Change the counter in Resource lists at the bottom left corner to say N {resource name} instead of N items_

## Reproduction steps

1. Open the compose admin page
2. See modules and charts

## Expected behavior 

_The counter at the bottom left corner should say N {resource name} instead of N items_

## Screenshot/Video

Image

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

### PR DESCRIPTION
**Pull request by yonkov**

### CODE REVIEW

File: client/web/admin/src/components/Apigw/CRouteList.vue [hunk 1]
```diff
@@ -30,6 +30,9 @@
         singlePluralPagination: 'admin:general.pagination.single',
         prevPagination: $t('admin:general.pagination.prev'),
         nextPagination: $t('admin:general.pagination.next'),
+        resourceSingle: $t('admin:general.route.single'),
```
Comment (Fajfa) [inline client/web/admin/src/components/Apigw/CRouteList.vue]: This should probably be done as the others(general:label.route)

File: client/web/admin/src/views/Automation/Session/List.vue [hunk 2]
```diff
@@ -22,6 +22,8 @@
         singlePluralPagination: 'admin:general.pagination.single',
         prevPagination: $t('admin:general.pagination.prev'),
         nextPagination: $t('admin:general.pagination.next'),
+        resourceSingle: $t('general:label.sessions.single'),
```
Comment (Fajfa) [inline client/web/admin/src/views/Automation/Session/List.vue]: The resource key should be singular (same for others), so sessions -> session

File: client/web/privacy/public/config.example.js [hunk 3]
```diff
@@ -1,12 +0,0 @@
...
-
-// CortezaAuth can be autoconfigured by replacing /api with /auth in CortezaAPI
-// or by appending /auth to the end of CortezaAPI string
-// When this is not possible and your configuration is more exotic you can set it
-// explicitly:
-// window.CortezaAuth = 'https://api.cortezaproject.your-domain.tld/auth';
-
-// Configure CortezaWebapp when your web applications are not placed on the root.
-// This is autoconfigured from the value of <base> tag href attribute in most cases.
-// window.CortezaWebapp = 'https://cortezaproject.your-domain.tld';
```
Comment (Fajfa) [inline client/web/privacy/public/config.example.js]: Why did you delete this?

File: locale/en/corteza-webapp-admin/automation.sessions.yaml [hunk 4]
```diff
@@ -51,4 +51,4 @@ list:
   loading: Loading sessions
   numFound: '{{count}} session found'
   numFound_plural: '{{count}} sessions found'
-  title: Sessions
```
Comment (Fajfa) [inline locale/en/corteza-webapp-admin/automation.sessions.yaml]: No changes needed here, please revert

File: locale/en/corteza-webapp-admin/system.connections.yaml [hunk 5]
```diff
@@ -8,6 +8,8 @@ primary:
 
 list:
   title: List of database connections
+  plural:
```
Comment (Fajfa) [inline locale/en/corteza-webapp-admin/system.connections.yaml]: This is not needed, since all labels are in general

File: locale/en/corteza-webapp-admin/system.queues.yaml [hunk 6]
```diff
@@ -43,4 +43,4 @@ list:
       label: Including
   loading: Loading messaging queues
   new: New
-  title: Messaging queues
```
Comment (Fajfa) [inline locale/en/corteza-webapp-admin/system.queues.yaml]: Same here, revert please. (You removed the last line of the file, and files need empty lines at the end)

File: locale/en/corteza-webapp-compose/general.yaml [hunk 7]
```diff
@@ -85,6 +85,10 @@ navigation:
   namespace: Namespaces
   module: Modules
   page: Pages
+  single:
```
Comment (Fajfa) [inline locale/en/corteza-webapp-compose/general.yaml]: To keep consistent, can you do it like you do in admin (general:label.resource.single/plural)

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: client/web/compose/src/views/Admin/Modules/Edit.vue [hunk 8]
```diff
@@ -254,7 +254,7 @@
                             <div
                               class="d-flex align-items-center"
                             >
-                              {{ $t('general.label.title') }}
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Modules/Edit.vue]: This shouldnt be changed

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
