### PR TITLE
Fix record deletion from the three dots dropdown not possible on Firefox

### LINKED ISSUE #973: Record deletion from the three dots dropdown not possible on Firefox Mozilla
## Description of the bug

_When you try to delete a record by clicking from the record list on the three dots and then pressing on the delete (trash can) button and then pressing on the red button doesn't work. When you press on the red button nothing happens._

## Reproduction steps

1. Open your record list in `Firefox`
2. Add a record
3. Now go on the record list and try to delete the record by clicking on the three dots on the right side of the record
4. Click on delete and press confirm (red button)
5. Notice that nothing happens

## Expected behavior 

_You should be able to delete a record without a problem._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/227504757-81f31a87-0c13-41c1-b524-f0b961050c14.mp4

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Atanas (Test Fest)
Browser: `This only happens of Mozilla Firefox, on other browsers it looks fine`

### PR DESCRIPTION
**Pull request by yonkov**
https://user-images.githubusercontent.com/26258032/230310013-af6a3cc5-42a7-42bc-a57f-37fb3f595cee.mp4

### CODE REVIEW

File: lib/vue/src/components/input/CInputConfirm.vue [hunk 1]
```diff
@@ -117,8 +116,8 @@ export default {
     },
 
     onCancel () {
-      this.inConfirmation = false
-      this.$emit('canceled')
+        this.inConfirmation = false
```
Comment (Fajfa) [inline lib/vue/src/components/input/CInputConfirm.vue]: Indent needs to be fixed

**Review by Fajfa — CHANGES_REQUESTED** [review]
