### PR TITLE
Fix reporter page block load elements error

### LINKED ISSUE #597: Having more than 2 elements in a reporter page block is giving an error
When I configure a reporter page block to have two elements, for example metrics and table, when I save the second element I am receiving the error `Failed to run report: expecting at most one definition, got 2`. Even though this error is displayed it looks like everything is functioning well.

https://user-images.githubusercontent.com/53232926/205629572-d9b5b8bf-2c00-4851-b883-48bb4351c23a.webm

### PR DESCRIPTION
**Pull request by KinyaElGrande**
# The following changes are implemented

More than one load element can be added to the reporter page block without   getting 
 `expecting at most one definition, got [number of elements]`  error message.

Fixes https://github.com/cortezaproject/corteza/issues/597

### CODE REVIEW

File: client/web/reporter/src/components/Report/Blocks/index.vue [hunk 1]
```diff
@@ -188,10 +188,14 @@ export default {
       this.dataframes = {}
       const frames = []
 
-      this.block.elements.forEach((element) => {
+      this.block.elements.forEach((element, key) => {
         element = reporter.DisplayElementMaker(element)
 
         if (element && element.kind !== 'Text') {
+          if (element.elementID === '0') {
```
Comment (Fajfa) [inline client/web/reporter/src/components/Report/Blocks/index.vue:195]: If it works its probably by accident, since how does the element.elementID match any names if that's not whats in the block element names

File: client/web/reporter/src/components/Report/Blocks/index.vue [hunk 2]
```diff
@@ -188,10 +188,14 @@ export default {
...
+            element.elementID = key.toString()
```
Comment (Fajfa) [inline client/web/reporter/src/components/Report/Blocks/index.vue]: Can be simplified by just doing `${key}`

File: client/web/reporter/src/components/Report/Blocks/index.vue (hunk 1 above)
Comment (KinyaElGrande) [reply client/web/reporter/src/components/Report/Blocks/index.vue:195]: `element.reportDefinitions` will assign the element.elementID to element's name https://github.com/cortezaproject/corteza/blob/79b414ecdbe85c9080b6ae12a5b4d220aeaba23a/client/web/reporter/src/components/Report/Blocks/index.vue#L199
