### PR TITLE
Fix for the glitch on page blocks being moved and resized

### LINKED ISSUE #1873: Check out why page blocks sometimes dont stay in place
https://forum.cortezaproject.org/t/page-builder-issues-reorganizing-blocks/2242

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/components/Common/Grid.vue [hunk 1]
```diff
@@ -142,15 +140,18 @@ export default {
...
-    },
-
     onLayoutUpdated () {
       this.resizing = false
+
+      this.blocks.forEach(({ xywh = [] }, idx) => {
+        const { x, y, w, h } = this.layout[idx]
+        const layoutXYWH = [x, y, w, h]
+
+        if (xywh.toString() === layoutXYWH.toString()) return
```
Comment (Fajfa) [inline client/web/compose/src/components/Common/Grid.vue:150]: This wont be ok since ['1','2','3'].toString is equal to ['1','23']. Best to just join with a separator and compare

File: client/web/compose/src/components/Common/Grid.vue [hunk 2]
```diff
@@ -120,9 +118,9 @@ export default {
       immediate: true,
       deep: true,
       handler (blocks) {
-        blocks = blocks.map(({ meta, xywh: [x, y, w, h] }, i) => {
+        blocks = blocks.map(({ title, meta, xywh: [x, y, w, h] }, i) => {
```
Comment (Fajfa) [inline client/web/compose/src/components/Common/Grid.vue]: Whats up with the title here?

**Review by Fajfa — CHANGES_REQUESTED** [review]
