### PR TITLE
Fix page builder not saving when tabs page block tab is removed

### LINKED ISSUE #1373: Unable to save page after removing pb first from tabs and then from the page itself
## Reproduction steps

_Reproducable only on already configured page like `Home` in CRM in qc_

I noticed that both the navigation pbs are affected after the pb is deleted (triangle icon appears in pb editor toolbar)

Image

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/views/Admin/Pages/Builder.vue [hunk 1]
```diff
@@ -743,24 +743,23 @@ export default {
...
 
       // Inline record lists
-      const queue = []
       this.usedBlocks.forEach((b, index) => {
         if (b.kind === 'RecordList' && b.options.editable) {
-          const p = new Promise((resolve) => {
-            const recordListUniqueID = [this.page.pageID, (this.record || {}).recordID, b.blockID, false].map(v => v || NoID).join('-')
-            this.$root.$emit(`page-block:validate:${recordListUniqueID}`, resolve)
-          })
+          const recordListModule = this.$store.getters['module/getByID'](b.options.moduleID)
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Pages/Builder.vue]: Use the getter with mapGetters

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
