### PR TITLE
Fix workflow delay step label and add format hint

### LINKED ISSUE #2250: Workflow - Delay function - Confusing expected format
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version of Corteza

2024.9.6

### Current Behavior

The delay function doesn't show clearly how it's meant to be used. It require trial and error from the user in it's current state.

Image

### Expected Behavior

The expected format is a string following the Duration type format, according to my finding at least. 

I propose reusing the workflow argument block with a Duration type indicator : 

Image

### Steps To Reproduce

_No response_

### Environment and versions

```markdown

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Mahjabin08**

### CODE REVIEW

File: client/web/workflow/src/components/Configurator/Delay.vue [hunk 1]
```diff
@@ -18,6 +18,7 @@
       >
         <b-form-group
           :label="$t('general:offset-expression')"
```
Comment (Fajfa) [inline client/web/workflow/src/components/Configurator/Delay.vue]: $t('configurator:delay.duration.label')

File: client/web/workflow/src/components/Configurator/Delay.vue [hunk 2]
```diff
@@ -18,6 +18,7 @@
...
+          :description="$t('configurator:delay.format-hint')"
```
Comment (Fajfa) [inline client/web/workflow/src/components/Configurator/Delay.vue]: $t('configurator:delay.duration.description')

File: locale/en/corteza-webapp-workflow/general.yaml [hunk 3]
```diff
@@ -24,7 +24,7 @@ new-workflow: New Workflow
 none: None
 now: Now
 offset: Offset
-offset-expression: Offset (expression)
+offset-expression: Duration
```
Comment (Fajfa) [inline locale/en/corteza-webapp-workflow/general.yaml]: Can we actually remove this (if its not used anywhere else)

File: locale/en/corteza-webapp-workflow/configurator.yaml [hunk 4]
```diff
@@ -25,3 +25,5 @@ run-as:
 sub-workflow:
   label: Subworkflow
   description: Subworkflows can't have enabled triggers
+delay:
```
Comment (Fajfa) [inline locale/en/corteza-webapp-workflow/configurator.yaml:28]: Match this file to the above comments

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: locale/en/corteza-webapp-workflow/general.yaml (hunk 3 above)
Comment (Mahjabin08) [reply locale/en/corteza-webapp-workflow/general.yaml]: I did a search, its not used anywhere else, so I think we can safely remove it
