### PR TITLE
Fix record create view page to opening on modal

### LINKED ISSUE #1370: Record create view opening behind modal instead of in the modal
## Reproduction steps

When the user clicks “+Add” without first entering the Contact Record’s Edit mode, the new blank Note Record page that the user should fill in and save opens on the main screen of Corteza behind the Contact Record modal. To complete creating the Note, the user needs to close the Contact Record modal.

https://user-images.githubusercontent.com/85161724/259354260-a9aa6e3c-59e9-4b89-85fe-6a9402ba61d4.mov

Alternately, the user needs to enter the Contact Record’s Edit mode, at which point clicking “+Add” to add a Note creates a new Note in the Notes Record List without the user having to leave the modal.

https://user-images.githubusercontent.com/85161724/259354605-7f0bba08-eabe-4258-a3fc-c339fafbf00c.mov

## Solution

The ideal solution would be to have the “+Add” button on the Record List function the same when NOT in the Record Page’s Edit mode as it currently does when in Edit mode without the main page of Corteza behind the modal changing Compose pages.

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/components/PageBlocks/RecordListBase.vue [hunk 1]
```diff
@@ -47,14 +47,15 @@
                 </template>
 
                 <template v-else-if="!inlineEditing && (recordPageID || options.allRecords)">
-                  <router-link
+                  <button
                     v-if="!options.hideAddButton"
                     data-test-id="button-add-record"
                     class="btn btn-lg btn-primary mr-1"
-                    :to="newRecordRoute"
+                    @click="handleNewRecordRoute()"
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/RecordListBase.vue]: lets rename it to `handleAddRecord`

File: client/web/compose/src/components/PageBlocks/RecordListBase.vue [hunk 2]
```diff
@@ -1884,6 +1870,29 @@ export default {
       this.showCustomPresetFilterModal = false
       this.selectedAllRecords = false
     },
+
+    handleNewRecordRoute () {
+      const refRecord = this.options.linkToParent ? this.record : undefined
+      const pageID = this.recordPageID
+
+      const route = {
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/RecordListBase.vue]: instead of defining the route here, just use is where you push

File: client/web/compose/src/components/PageBlocks/RecordListBase.vue [hunk 3]
```diff
@@ -1884,6 +1870,29 @@ export default {
...
+        query: null,
+      }
+
+      if (pageID || this.options.rowCreateUrl) {
+        if (this.isModal) {
+          this.$root.$emit('show-record-modal', {
+            recordID: NoID,
+            recordPageID: this.recordPageID,
+          })
+          return
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/RecordListBase.vue]: Instead of returning, do `else`

File: client/web/compose/src/components/PageBlocks/RecordListBase.vue [hunk 4]
```diff
@@ -1884,6 +1870,29 @@ export default {
...
+      const refRecord = this.options.linkToParent ? this.record : undefined
+      const pageID = this.recordPageID
+
+      const route = {
+        name: this.options.rowCreateUrl || 'page.record.create',
+        params: { pageID, refRecord },
+        query: null,
+      }
+
+      if (pageID || this.options.rowCreateUrl) {
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/RecordListBase.vue]: Turn this into a guard `if (!(pageID && this.options.rowCreateUrl)) return

File: client/web/compose/src/components/PageBlocks/base.vue [hunk 5]
```diff
@@ -94,6 +94,12 @@ export default {
     autoRefreshEnabled () {
       return this.options.refreshRate >= 5 && ['page', 'page.record'].includes(this.$route.name)
     },
+
+    isModal () {
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/base.vue]: Lets rename this to something that better describes it. 
isModal means the thing is a modal, which this is not. 
It should rather be something like `inModal` if you want to keep it short
A comment above describing it also helps

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]

**Review by Fajfa — APPROVED** [review]
