### PR TITLE
Fixes CInputSelect prop type errors

### LINKED ISSUE #1641: Fix user and record selector c-input-select error
Image

### PR DESCRIPTION
**Pull request by EmmyMay**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/components/ModuleFields/Editor/Record.vue [hunk 1]
```diff
@@ -297,7 +295,7 @@ export default {
     getRecord (index = undefined) {
       const value = index !== undefined ? this.value[index] : this.value
       if (value) {
-        return this.convert({ recordID: value })
+        return this.convert({ recordID: value }).value
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/Record.vue]: Whenever you do a .value, you need to be sure that what you're reading from is always an object and can never be undefined

File: client/web/compose/src/components/ModuleFields/Editor/Record.vue [hunk 2]
```diff
@@ -506,10 +504,26 @@ export default {
...
     },
 
-    getOptionKey ({ value }) {
+    findRecord (recordID) {
+      return this.options.find(r => r.value === recordID)
+    },
+
+    getOptionKey (v) {
+      if (typeof v === 'string') {
+        return this.options.find(r => r.value === v).value
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/Record.vue]: Pretty sure you can just return v here

File: client/web/compose/src/components/ModuleFields/Editor/Record.vue [hunk 3]
```diff
@@ -506,10 +504,26 @@ export default {
...
+      }
+      const { value } = v || {}
       return value
     },
 
+    getOptionLabel (v) {
+      if (typeof v === 'string') {
+        return this.findRecord(v).label
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/Record.vue]: Same here ->Whenever you do a .value, you need to be sure that what you're reading from is always an object and can never be undefined

File: client/web/compose/src/components/ModuleFields/Editor/Record.vue [hunk 4]
```diff
@@ -506,10 +504,26 @@ export default {
       this.filter.pageCursor = next ? this.filter.nextPage : this.filter.prevPage
     },
 
-    getOptionKey ({ value }) {
+    findRecord (recordID) {
+      return this.options.find(r => r.value === recordID)
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/Record.vue]: Fallbacks, fallbacks, fallbacks

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 5]
```diff
@@ -268,11 +268,20 @@ export default {
...
+        return user
+      }
+      return user.userID
     },
 
-    getOptionLabel ({ userID, email, name, username }) {
+    getOptionLabel (user) {
+      if (typeof user === 'string') {
+        const { name, username, email, userID } = this.findByID(user) || {}
+        return name || username || email || `<@${userID}>`
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: I see 2 things that repeat, can we make it so that isn't true?

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 6]
```diff
@@ -319,7 +328,7 @@ export default {
     getUserByIndex (index = 0) {
       const userID = this.field.isMulti ? this.value[index] : this.value
       if (userID) {
-        return this.findByID(userID) || {}
+        return this.findByID(userID).userID || {}
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: if it doesn't find the user it will be undefined, so same as above applies.
Also why the `|| {}`, if what you're returning is a userID?

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 7]
```diff
@@ -319,7 +328,7 @@ export default {
     getUserByIndex (index = 0) {
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: Shouldn't this be renamed now? Since its actually getting the userID?

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 8]
```diff
@@ -276,12 +276,8 @@ export default {
     },
 
     getOptionLabel (user) {
-      if (typeof user === 'string') {
-        const { name, username, email, userID } = this.findByID(user) || {}
-        return name || username || email || `<@${userID}>`
-      }
-
-      const { name, username, email, userID } = user || {}
+      user = typeof user === 'string' ? this.findByID(user) || {} : user || {}
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: No need to fallback here, you need to fallback when you're using it

```
if (typeof user === 'string') {
  user = this.findByID(user)
}
const { name, username, email, userID } = user || {}
...
```

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 9]
```diff
@@ -325,10 +321,10 @@ export default {
      * Retrives user (via value) from record field
      * Handles single & multi value fields
      */
-    getUserByIndex (index = 0) {
+    getUserID (index = 0) {
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: can you keep the ByIndex part please

File: client/web/compose/src/components/ModuleFields/Editor/User.vue [hunk 10]
```diff
@@ -325,10 +321,10 @@ export default {
...
       const userID = this.field.isMulti ? this.value[index] : this.value
       if (userID) {
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/User.vue]: no need for an if here, you can just return the `this.field.isMulti ? this.value[index] : this.value`. 
Since otherwise it returns undefined anyway

File: client/web/compose/src/components/ModuleFields/Editor/Record.vue [hunk 11]
```diff
@@ -295,7 +295,10 @@ export default {
     getRecord (index = undefined) {
       const value = index !== undefined ? this.value[index] : this.value
       if (value) {
-        return this.convert({ recordID: value }).value
+        const { value: v } = this.convert({ recordID: value })
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Editor/Record.vue]: This is all that is needed 
```
const recordID = index !== undefined ? this.value[index] : this.value
return (this.convert({ recordID }) || {}).value
```

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
