### PR TITLE
Apply preview styles from file page block to module field

### LINKED ISSUE #988: File upload default configuration not preserved
## Description of the bug

_When you create a file upload field and you don’t touch it’s configurations (height, width) and then on public page you upload a picture, the picture is displayed okay. But later if you let’s say put `100` on all the places, for width, height, after that If I go to my public page, I see my picture enlarged, but when I go back if I want to return the picture to its original state/size and if I delete all of the numbers there, I expect the size to go to the original one, but upon saving the numbers go to zero and the picture is not shown because the height and width is actually zero._

## Reproduction steps

•	Have a file upload field
•	Don’t change anything in the configuration
•	Upload a picture
•	Go back in module and in field configuration change the width and height
•	Go back to public page notice that the picture has changed
•	Now go back again and erase all of your configurations for the size and press save
•	Now see that the picture is not shown since the size and width is actually zero.

## Expected behavior 

_When I erase all the numbers I expect them to go back to normal as in the beginning when we create the file upload field._

## Screenshot/Video

•	When I erase all of the configurations for height, width..

Image

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Bojan (Test fest)
Browser: Edge

### PR DESCRIPTION
**Pull request by katrinDY**
# The following changes are implemented
Applied preview styles from file page block to module field

# Changes in the user interface:
Both interfaces are identical now

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

**Comment by katrinDY** [comment]
Proposed changes in the last commit: (description for preview section added and placeholder so feature is more user friendly). Can apply these changes in FileBase as well
Screenshot 2023-03-29 at 14 54 50

File: client/web/compose/src/components/ModuleFields/Configurator/File.vue [hunk 1]
```diff
@@ -103,18 +95,13 @@
...
-              :append="$t('kind.file.view.px')"
-            >
-              <b-form-input
-                v-model="f.options.maxHeight"
-                type="number"
-                number
-                :placeholder="$t('kind.file.view.maxHeight')"
-              />
-            </b-input-group>
+            <b-form-input
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Configurator/File.vue:99]: Make sure you update the File block aswell, since they use same translations.
I would also not use placeholders here

**Review by Fajfa — CHANGES_REQUESTED** [review]
