### PR TITLE
Cast numeric datatype to text for 'like' and 'not like' filters in Postgre

### LINKED ISSUE #1305: Postgre error when trying to filter a record using 'Not equal', 'Like', 'Not like'
## Error

Image

## Reproduction steps

Image

### PR DESCRIPTION
**Pull request by KinyaElGrande**
Ref: https://github.com/cortezaproject/corteza/issues/1305

The following PR fixes the issue with PostgreSQL's `like` and `not like` filters on numeric values.

### CODE REVIEW

File: server/store/adapters/rdbms/drivers/postgres/dialect.go [hunk 1]
```diff
@@ -217,20 +217,24 @@ func (postgresDialect) AttributeToColumn(attr *dal.Attribute) (col *ddl.Column,
...
-		return exp.NewSQLFunctionExpression("CONCAT", aa...), nil
+		return castColumnDataToText("CONCAT", args...)
 
 	case "in":
 		return drivers.OpHandlerIn(d, n, args...)
 
 	case "nin":
 		return drivers.OpHandlerNotIn(d, n, args...)
 
+	case "like", "nlike":
```
Comment (tjerman) [inline server/store/adapters/rdbms/drivers/postgres/dialect.go:228]: What about cases where the type is not ID? Should it return nothing? Is that OK?
Also, is the AttributeTypeID the only one? There are some other numeric types defined,

**Review by tjerman — COMMENTED** [review]
Check my comment; if it's ok then this lgtm; else fix :ok_hand:

**Review by tjerman — APPROVED** [review]
LGTM; good job
