### PR TITLE
Fix handle not unique issue on page layout copy

### LINKED ISSUE #1228: Saving a layout as a copy doesn't work
## Description of the bug

_When you want to make a copy of your existing record page, you are not able to and you are receiving the error message: `Failed to clone layout: handle not unique`_

## Reproduction steps

1. Open a namespace that has an existing page
2. Open the page builder of your page from your admin panel
3. Press on Save as copy
4. Notice that the copy doesn't work and you are receiving an error

## Expected behavior 

_Since the future is there, I should be able to copy a page and have an exact copy of my layout/page._

## Screenshot/Video

Image

## Version

Branch: 2023.3.x

### PR DESCRIPTION
**Pull request by katrinDY**
# The following changes are implemented
Layout issue was fixed

# Changes in the user interface:
None

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/views/Admin/Pages/Builder.vue [hunk 1]
```diff
@@ -779,7 +779,7 @@ export default {
 
       layout.meta.title = `${layout.meta.title}`
 
-      this.createPageLayout(this.layout).then(({ layoutID }) => {
+      this.createPageLayout(layout).then(({ layoutID }) => {
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Pages/Builder.vue]: Why this layout? The layout is created three lines above, and that one should be used

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: client/web/compose/src/views/Admin/Pages/Builder.vue (hunk 1 above)
Comment (Fajfa) [reply client/web/compose/src/views/Admin/Pages/Builder.vue]: This is a case of me being blind, all good

**Review by Fajfa — APPROVED** [review]
