### PR TITLE
Fix overflow issue in RecordOrganizer

### LINKED ISSUE #1209: Record organizer overflowing long texts
Image

### PR DESCRIPTION
**Pull request by katrinDY**
# The issue is present in the fields:
- record
- email
- url

# The following changes are implemented
Longer texts don't overlap container for the fields record, email, url

# Changes in the user interface:
None

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/components/ModuleFields/Viewer/Record.vue [hunk 1]
```diff
@@ -9,7 +9,6 @@
     <span
       v-for="(v, index) of formattedValue"
       :key="index"
-      class="text-nowrap"
```
Comment (Fajfa) [inline client/web/compose/src/components/ModuleFields/Viewer/Record.vue]: Am doubtful this won't impact other places where we use record viewer, the only changes should be in record organizer base

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
