### PR TITLE
Fix error for unconfigured sources

### LINKED ISSUE #766: Unconfigured source in geometry field causing issues
## Steps to reproduce
1. Create a geometry page block
2. Add a source event without selecting a module
3. See error in the console

Image

## Expected behaviour
We shouldn't save unconfigured sources

### Requirements

- [x] Geometry field should be required for isValid check
- [x] Change order of inputs to Select, Geometry field, title, prefilter ....
- [x] Change Select module to Select
- [x] Module and Geometry field should be asterisked

### PR DESCRIPTION
**Pull request by EmmyMay**
https://github.com/cortezaproject/corteza/issues/766

### CODE REVIEW

File: client/web/compose/src/components/PageBlocks/GeometryBase.vue [hunk 1]
```diff
@@ -149,7 +149,7 @@ export default {
         zoomMax,
       }
 
-      Promise.all(this.options.feeds.map((feed, idx) => {
+      Promise.all(this.options.feeds.filter(({ options }) => options.moduleID !== NoID).map((feed, idx) => {
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/GeometryBase.vue]: I doubt this is the only thing needed for it to function no? You also need other configurations so, I would suggest you add a isValid method to the feeds and do it like this.options.feed.filter(f => f.isValid())

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: lib/js/src/compose/types/page-block/geometry/feed.ts [hunk 2]
```diff
@@ -53,4 +53,8 @@ export default class Feed {
       }
     }
   }
+
+  isValid (): boolean {
+    return this.options.moduleID !== NoID
```
Comment (Fajfa) [inline lib/js/src/compose/types/page-block/geometry/feed.ts]: This is not the only thing needed in the feed for it to be valid. Try configuring it and see, might also be worth adding a * next to the required values (in the form next to labels))

Otherwise this is the right approach

**Review by Fajfa — CHANGES_REQUESTED** [review]

File: client/web/compose/src/components/PageBlocks/GeometryConfigurator/FeedSource/configs/Record.vue [hunk 3]
```diff
@@ -28,16 +28,21 @@
...
-          <b-input-group>
-            <b-form-input
-              v-model="feed.options.color"
-              style="max-width: 50px;"
-              type="color"
-              debounce="300"
-            />
-          </b-input-group>
+          <b-form-select
+            v-model="feed.geometryField"
```
Comment (EmmyMay) [inline client/web/compose/src/components/PageBlocks/GeometryConfigurator/FeedSource/configs/Record.vue:34]: Here you can see the v-model is tied to the geometryField not the deeper options.geometryField

File: lib/js/src/compose/types/page-block/geometry/feed.ts [hunk 4]
```diff
@@ -53,4 +53,8 @@ export default class Feed {
       }
     }
   }
+
+  isValid (): boolean {
+    return this.options.moduleID !== NoID && this.geometryField !== ''
```
Comment (EmmyMay) [inline lib/js/src/compose/types/page-block/geometry/feed.ts]: https://github.com/cortezaproject/corteza/blob/8a7a10edaccb4b9d271ec4e100e22201c5c3e27a/lib/js/src/compose/types/page-block/geometry/feed.ts#L10

I noticed that the geometryField options is not updated when a field is not selected. My question is should it even be in the options? It either looks like we have two identical things and we only really need one or we are not updating it as we should. Or maybe I am the one missing something

**Review by Fajfa — APPROVED** [review]
