### PR TITLE
Fix optional and configured TOTP not prompting when loggin in

### LINKED ISSUE #2200: Fix optional TOTP
Not being prompted to enter TOTP when configured. If enforced it works ok
Also if disabling TOTP in Profile screen you get redirected back to TOTP configure screen

### PR DESCRIPTION
**Pull request by Fajfa**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

File: server/auth/handlers/handle_mfa_totp.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ func (h AuthHandlers) mfaTotpDisableProc(req *request.AuthReq) (err error) {
 
 		// Make sure we update User's data in the session
 		req.AuthUser.User = user
-		req.AuthUser.ResetTOTP()
+		req.AuthUser.Update(h.Settings, user)
```
Comment (tjerman) [inline server/auth/handlers/handle_mfa_totp.go:186]: What does this do?

File: server/auth/handlers/handle_security.go [hunk 2]
```diff
@@ -51,6 +51,7 @@ func (h *AuthHandlers) securityProc(req *request.AuthReq) error {
 
 			// Make sure we update User's data in the session
 			req.AuthUser.User = user
+			req.AuthUser.Update(h.Settings, user)
```
Comment (tjerman) [inline server/auth/handlers/handle_security.go:55]: What does this do?

**Review by tjerman — CHANGES_REQUESTED** [review]

File: server/auth/handlers/handle_mfa_totp.go (hunk 1 above)
Comment (Fajfa) [reply server/auth/handlers/handle_mfa_totp.go:186]: Prevents stale data and fixes redirects based on that stale data

File: server/auth/handlers/handle_security.go (hunk 2 above)
Comment (Fajfa) [reply server/auth/handlers/handle_security.go:55]: Prevents stale data and fixes redirects based on that stale data
