### PR TITLE
Remove none from fill/justify options on tab configurator

### LINKED ISSUE #1060: Have just one fill/justify and none option in tabs and navigation blocks
## Description of the bug

_Tabs block, no difference between fill and justify option_

## Proposed solution

_Let's have just one option which will be either fill or justify and none._

## Reproduction steps

Add tabs block and change fill or justify to fill. Nothing happens.

## Expected behavior 

_It should be more understandable what these styling options do and it seems like they are not working at all. We need to consider if we need this feature at all, as it seems to only confuse at this point? Moreover, it would be good to specify if the styling options are for the tabs themselves or for the blocks inside the tabs_

## Screenshot/Video

Image

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Atanas (Test fest)
Browser: Firefox

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/components/PageBlocks/TabsConfigurator.vue [hunk 1]
```diff
@@ -282,7 +282,6 @@ export default {
         fillJustify: [
           { text: this.$t('tabs.style.fillJustify.fill'), value: 'fill' },
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/TabsConfigurator.vue]: Remove fill or justify, not none. 
This also needs to be done in navigation configurator.

File: client/web/compose/src/components/PageBlocks/Navigation/Base.vue [hunk 2]
```diff
@@ -6,11 +6,13 @@
...
-        :tabs="options.display.appearance === 'tabs'"
-        :pills="options.display.appearance === 'pills'"
-        :small="options.display.appearance === 'small'"
-        :fill="options.display.fillJustify === 'fill'"
-        :justify="options.display.fillJustify === 'justify'"
+        v-bind="{
+          tabs: options.display.appearance === 'tabs',
+          pills: options.display.appearance === 'pills',
+          small: options.display.appearance === 'small',
+          fill: options.display.fillJustify === 'fill',
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/Navigation/Base.vue]: Remove fill or justify, whichever is less useful. Same needs to be done in tabs

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
