### PR TITLE
Resolve blocks being hidden forever

### LINKED ISSUE #985: Hidden blocks can become invisible forever
## Description of the bug

_When you remove or delete a block within the Tabs configuration, it does not return to the layout, but it will stay hidden. If you subsequently remove the entire tab block, those blocks are still on the page, but invisible forever._

## Reproduction steps

1.	Create a couple of page blocks. It does not matter which ones.
2.	Create a Tab block.
3.	Add the page blocks created before to tabs under the “Tabs” tab 🙂
4.	Optionally, hit save and close (to see that they work)
5.	In the Tabs configuration, empty one tab by clicking on the X.
6.	For another tab, select a different page block
7.	For the last tab, hit the delete button
Those block will not return to the page layout. And if you would delete the Tab block, they will not come back either.

## Expected behavior 

_Whenever a page block is not forming part of the Tabs block anymore, it must return to the page layout._

## Screenshot/Video

Image

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Lenny (Test fest)
Browser: Firefox

### PR DESCRIPTION
**Pull request by EmmyMay**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

Closes #985

### CODE REVIEW

File: client/web/compose/src/components/PageBlocks/TabsBase.vue [hunk 1]
```diff
@@ -81,7 +81,7 @@ export default {
   computed: {
     tabbedBlocks () {
       return this.block.options.tabs.map(({ blockID, title }) => {
-        let block = this.blocks.find(b => fetchID(b) === blockID)
+        let block = JSON.parse(JSON.stringify(this.blocks.find(b => fetchID(b) === blockID)))
 
         // Blocks should display as Plain, to avoid card shadow/border
         if (block) {
```
Comment (Fajfa) [inline client/web/compose/src/components/PageBlocks/TabsBase.vue]: Can you remove the border aswell, like we do with Plain

File: client/web/compose/src/views/Admin/Pages/Builder.vue [hunk 2]
```diff
@@ -623,13 +622,49 @@ export default {
...
 
+    showUnusedHiddenBlocks () {
+      const hiddenBlocks = new Set()
+      const allTabBlocks = this.blocks.filter(({ kind }) => kind === 'Tabs')
+      let found = 0
+
+      this.blocks.forEach(block => {
+        if (!block.meta.hidden) return
+
+        hiddenBlocks.add(fetchID(block))
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Pages/Builder.vue]: You dont need to add it to the set, instead just process it immediately.

File: client/web/compose/src/views/Admin/Pages/Builder.vue [hunk 3]
```diff
@@ -623,13 +622,49 @@ export default {
...
+      })
+
+      // Go through all hidden blocks to find where they are unused
+      hiddenBlocks.forEach(blockID => {
+        found = 0
+        allTabBlocks.forEach(tabBlock => {
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Pages/Builder.vue]: This can be replaced with some

File: client/web/compose/src/views/Admin/Pages/Builder.vue [hunk 4]
```diff
@@ -623,13 +622,49 @@ export default {
...
+          const { tabs } = tabBlock.options
+
+          if (!tabs.length) return
+
+          const tab = tabs.find(({ blockID: tabBlockID }) => tabBlockID === blockID)
```
Comment (Fajfa) [inline client/web/compose/src/views/Admin/Pages/Builder.vue]: same here, you can replace it with some

**Review by Fajfa — CHANGES_REQUESTED** [review]

**Review by Fajfa — APPROVED** [review]
