### PR TITLE
Fix date record list filter for between operators

### LINKED ISSUE #939: Fix date record list filter for between/not between operators
Fix date record list filter for between/not between operators

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
Fix date record list filter for between operators

# Changes in the user interface:

# Checklist when submitting a final (!draft) PR
 - [x] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [x] Code builds
 - [x] All existing tests pass
 - [x] All new critical code is covered by tests
 - [x] PR is linked to the relevant issue(s)
 - [x] Rebased with the target branch

### CODE REVIEW

File: client/web/compose/src/lib/record-filter.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ export function getFieldFilter (name, kind, query = '', operator = '=') {
   let boolQuery = query
   let numQuery = query
 
-  if (typeof query === 'object' && query !== null) {
+  if (typeof query !== 'object' && query !== null) {
     boolQuery = toBoolean(query)
```
Comment (Fajfa) [inline client/web/compose/src/lib/record-filter.js:36]: Probably makes sense to move this right after line 60, since you don't need it anywhere else.

**Review by Fajfa — CHANGES_REQUESTED** [review]
